# DESCRIPTION:
#  A workflow used to get Go dependencies and test code
# END

name: Go CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review  
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20

    - name: Download Go dependencies
      run: go get  ./... && go mod tidy

    - name: Test code
      run: go test -v ./...
