# DESCRIPTION:
#  A workflow used to get Go dependencies and test code
# END

name: PR CI

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review  
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Set up Go
      uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4
      with:
        go-version: '1.20.x'

    - name: Download Go dependencies
      run: go get  ./... && go mod tidy

    - name: Check if all dependencies were commited
      shell: bash
      run: |
          if [ "$(git status --porcelain)" ]; then 
            git status
            exit 1
          else
            exit 0
          fi

    ### Uncomment it, when tests are prepared
    # - name: Test code
    #   run: go test -v ./...
