# DESCRIPTION:
#  A workflow used to get Go dependencies and test code
# END

name: PR CI

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review  
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

    - name: Set up Go
      uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3
      with:
        go-version: '1.20.x'

    - name: Download Go dependencies
      run: go get  ./... && go mod tidy

    - name: Check if all dependencies were commited
      shell: bash
      run: |
          if [ "$(git status --porcelain)" ]; then 
            git status
            exit 1
          else
            exit 0
          fi

    ### Uncomment it, when tests are prepared
    # - name: Test code
    #   run: go test -v ./...
