name: Release CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * 4" # this means every Thursday @1am UTC

jobs:
  release-prereqs:
    name: verify if a release is required
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
    outputs:
      rc: ${{ steps.rc.outputs.new_release_published }}
    steps:
      - name: checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: dry-run sem versioning
        id: rc
        uses: cycjimmy/semantic-release-action@0a51e81a6baff2acad3ee88f4121c589c73d0f0e # v4
        with:
          dry_run: true
          semantic_version: 19.0
          extra_plugins: |
            https://gitpkg.vercel.app/conventional-changelog/conventional-changelog/packages/conventional-changelog-conventionalcommits?ba6df7cf62de5f448368bed4398f6ddf633d2cbd
            semantic-release/git#3e934d45f97fd07a63617c0fc098c9ed3e67d97a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: sem ver outputs
        run: |
          echo new_release_published - ${{ steps.rc.outputs.new_release_published }}
          echo new_release_version - ${{ steps.rc.outputs.new_release_version }}
          echo last_release_version - ${{ steps.rc.outputs.last_release_version }}

  release:
    name: release sem version
    needs:
      - release-prereqs
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
    steps:
      - name: checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Create release and publish
        uses: cycjimmy/semantic-release-action@0a51e81a6baff2acad3ee88f4121c589c73d0f0e # v4
        with:
          semantic_version: 19.0
          extra_plugins: |
            https://gitpkg.vercel.app/conventional-changelog/conventional-changelog/packages/conventional-changelog-conventionalcommits?ba6df7cf62de5f448368bed4398f6ddf633d2cbd
            semantic-release/git#3e934d45f97fd07a63617c0fc098c9ed3e67d97a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
